### ISSUE TITLE
继之前的一个问题

### ISSUE THREAD

**Issue by FanYuanBo888** [AAChartKit/AAChartKit#24]
差不多需要这个效果，然后点击的效果依然存在，可以实现吗？
<img width="269" alt="2017-05-31 15 56 59" src="https://cloud.githubusercontent.com/assets/28720260/26621581/d262f8c0-4619-11e7-9ae2-69d78b14a322.png">

**Comment by AAChartModel** [comment]
AAChartKit的 demo 中已有类似示例效果.
