### ISSUE TITLE
悬浮窗如何实现多种类型数据的展示?

### ISSUE THREAD

**Issue by ChaoYug** [AAChartKit/AAChartKit#408]
你好,想实现悬浮窗展示多种类型的数据,如下图所示,不知道AAChartKit能否实现?目前在demo中并没有看到类似的效果.感谢解惑!
![1535332847916](https://user-images.githubusercontent.com/20300751/44635840-e719ea00-a9da-11e8-8509-26aa460f2a0d.jpg)

**Comment by AAChartModel** [comment]
Highcharts 里应该是有的,但是 AAChartKit 里目前没有.
不过官网的示例中我也没有看到过.

**Comment by AAChartModel** [comment]
你这个不是 echart 的效果吗?

**Comment by ChaoYug** [comment]
不太清楚具体用的什么,从前端那边截图过来的.

**Comment by ChaoYug** [comment]
感谢答疑

**Comment by AAChartModel** [comment]
看着这个样式,前端那边,明显用的是 echart 啊,你可以直接嵌入 echart, 这样做的话,你和前端两边数据同步起来也方便,出了问题容易讨论.而且 echart 还有不同的版本,你最好先问清楚了. echart 好像也有 iOS 封装的.你在网络上搜索一下即可.从你目前的需求来看,最合适你的应该不是 AAChartKit.嵌入echart 是最佳选择

**Comment by ChaoYug** [comment]
好的,谢谢建议,但目前大部分的图表需求aachartkit还是非常能胜任的,echarts和设计图还是有较大的出入.

**Comment by AAChartModel** [comment]
你使用echarts的话,你公司前端的所有相关图表配置,你能够直接套过来用的, AAChartKit 的话,你还需要自己去调

**Comment by AAChartModel** [comment]
除非你们公司前端都换成 Highcharts 了,那就另说了
