### ISSUE TITLE
这个x轴内容不能像0，1，2，3自动生成的坐标一样起点是原点呢?

### ISSUE THREAD

**Issue by Lilintao916** [AAChartKit/AAChartKit#409]
设置了上述categoriesSet这个X轴的起始点就不能是原点了,但是不设置这个X轴的内容,默认是原点开始绘制,我想设置X轴内容之后,还是从原点开始可以吗?

**Comment by Lilintao916** [comment]
AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:_aaChartModel];
    aaOptions.xAxis.tickmarkPlacement = @"on";
    [self.aaChartView aa_drawChartWithOptions:aaOptions];

这样只是控制点在轴线上,但是距离原点还是有一段距离的

**Comment by AAChartModel** [comment]
已在 AAChartKit 中的 AAChartView.html 文件中添加了如下代码内容

```js
                var categories = aaOptions.xAxis.categories;
                aaOptions.xAxis.categories = null;//这一句代码很关键,如果没有则 categories 文字无法显示,应该是highcharts的小bug
                if (categories) { //设置有 categories 时,X轴刻度线始终对齐 categories 的文字内容
                    aaOptions.xAxis.labels = {
                        formatter: function() {
                            return categories[this.value];
                        }
                    };
                }
```

你更新一下AAChartKit 的 demo, 运行查看一下效果,看看是否和你给的这个链接的效果相吻合

**Comment by Lilintao916** [comment]
我更新了一下demo并没有在html文件找到这段代码..

**Comment by Lilintao916** [comment]
https://github.com/AAChartKit/AAChartKit.git

**Comment by AAChartModel** [comment]
不好意思,一次性提交的文件有点多,竟然给漏了,现在已经添加上了 提交内容在这里 df0c3d0,你更新并运行查看一下效果.

**Comment by Lilintao916** [comment]
已经达到效果了,谢谢~麻烦了

**Comment by Lilintao916** [comment]
好像出问题了,现在的添加那段代码之后 浮动框的提示不是X轴的文字了 已经变成 0,1,2,4,...了

**Comment by Lilintao916** [comment]
而且那段代码添加之后,饼状图绘制不出来了,注释点就好了,

**Comment by AAChartModel** [comment]
坑爹啊,我后来又仔细看了一下,你给的链接中的那个示例本身就是是有问题的,压根就不是一个值得参考的范本.其实只要 AAXAxis类添加这部分初始化的时候的默认值即可

```objective-c
- (instancetype)init {
    self = [super init];
    if (self) {
        _min = @0;
        _tickmarkPlacement = @"on";//本参数只对分类轴有效。 当值为 on 时刻度线将在分类上方显示；当值为 between 时，刻度线将在两个分类中间显示。当 tickInterval 为 1 时，highcharts官方默认是 between,我这里手动将其改为 on
    }
    return self;
}

```

我已将之前的代码删除了,添加了这部分新的内容.你还是要更新一下,在运行查看效果吧

**Comment by AAChartModel** [comment]
其实参考这里的内容就可以了 https://blog.csdn.net/u012884402/article/details/49867639

**Comment by Lilintao916** [comment]
和之前一样啊,没有效果..

self.aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(chartType)//图表类型
    .categoriesSet(self.titlesArr)
    .colorsThemeSet(@[@"#ff6666",@"#f8b551",@"#48a0ec",@"#7dffc0"])//设置主体颜色数组

    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:_aaChartModel];
    aaOptions.xAxis.tickmarkPlacement = @"on";
    [self.aaChartView aa_drawChartWithOptions:aaOptions];

**Comment by AAChartModel** [comment]
我猜你可能要换个库了, Highcharts 我压根就找不到设置了 categories 之后,还能让x 轴刻度从0开始的.!!!流汗

**Comment by AAChartModel** [comment]
修改 AAChartView.html 文件内容的方法也有缺陷, tooltip 上的标题内容也是无法显示 categories 文字
