### ISSUE TITLE
xcode warning: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

### ISSUE THREAD

**Issue by wyk111wyk** [AAChartKit/AAChartKit#414]
<img width="944" alt="2018-08-29 11 21 55" src="https://user-images.githubusercontent.com/8171481/44761369-d0f85f00-ab7d-11e8-8b32-5e8ff6418032.png">

**Comment by AAChartModel** [comment]
这个⚠️警告是最新版本的 xcode 的问题

**Comment by AAChartModel** [comment]
参考 https://www.jianshu.com/p/fcb51ee4ad72
