### ISSUE TITLE
如何实现柱状图 dataLabel 不同的颜色？

### ISSUE THREAD

**Issue by wncios** [AAChartKit/AAChartKit#415]
![](http://ww1.sinaimg.cn/large/005CeeMAgy1furisxhkwgj30bg07t0t0.jpg)

如图所示，请问作者，我该怎么实现圈中区域的 dataLabel 文字颜色为红色呢？左边为绿色右边为红色，和柱子颜色一样

**Comment by AAChartModel** [comment]
这个歌恐怕无法支持,你可能要另寻良方了
