### ISSUE TITLE
bar Chart 条形图可以每个条形颜色单独设置吗，如图

### ISSUE THREAD

**Issue by Ssssssy** [AAChartKit/AAChartKit#418]
![image](https://user-images.githubusercontent.com/18344798/44977883-e1547380-af9b-11e8-897a-1014ff3c1b24.png)

**Comment by AAChartModel** [comment]
支持彩色的条形图📊,具体参见 demo 内容,里面有彩色的柱状图示例.关键属性就是 `AASeriesElement` 的 `colorByPoint`
