### ISSUE TITLE
怎样将y轴显示的罗马数字转换为阿拉伯数字呢?自定义y轴lable

### ISSUE THREAD

**Issue by zhouzhou94alone** [AAChartKit/AAChartKit#419]
![2018-09-04 15 10 01](https://user-images.githubusercontent.com/17922986/45016272-b844e900-b056-11e8-8b25-b6764af1828f.png)

**Comment by AAChartModel** [comment]
抱歉,datalabel的数字改成罗马数字恐怕做不到

**Comment by zhouzhou94alone** [comment]
哦 谢谢 可以优化下就更完美了 🆙

**Comment by zhouzhou94alone** [comment]
哦 谢谢 可以优化下就更完美了 🆙
