### ISSUE TITLE
提示框显示效果可以修改吗

### ISSUE THREAD

**Issue by HouSaiYinKay** [AAChartKit/AAChartKit#420]
作者大大,问一下哪里可以修改提示框的显示时长,就是显示提示框后手指离开屏幕,提示框自动消失的效果,蛋疼的需求

**Comment by AAChartModel** [comment]
恐怕不行

https://api.hcharts.cn/highcharts#tooltip.hideDelay  设置隐藏延时时间的这个属性在手机上无效.

**Comment by HouSaiYinKay** [comment]
好吧,回复好快,给你个赞

**Comment by AAChartModel** [comment]
https://www.hcharts.cn/docs/basic-tooltip/

https://api.hcharts.cn/highcharts#tooltip

这两处链接指向的地址,是 tooltip 的所有相关属性内容,并未发现你说的接口
