### ISSUE TITLE
如何设置隐藏图标的name属性

### ISSUE THREAD

**Issue by sheyingying** [AAChartKit/AAChartKit#461]
.seriesSet(@[
                     AAObject(AASeriesElement)
                     .lineWidthSet(@.5)
                     .fillOpacitySet(@.7)
                     .nameSet(@"")
这个设置中的name如何设置隐藏

**Comment by AAChartModel** [comment]
```objc
AAPropStatementAndPropSetFuncStatement(assign, AAChartModel, BOOL, legendEnabled) //是否显示图例 lengend(图表底部可点按的圆点和文字)
```

想要完全隐藏 legend 图例的话,设置legendEnabled布尔属性为 NO 即可

**Comment by sheyingying** [comment]
哈哈~我是妹子。出国了一周所以有点慢啊 @AAChartModel
