### ISSUE TITLE
求助大佬一个问题，如何调整曲线的上下幅度？

### ISSUE THREAD

**Issue by wncios** [AAChartKit/AAChartKit#468]
例如，有而是个数字，均在10～11之间，全都小数点类型。这个时候无论加载柱状图还是折线图上下的幅度都几乎是全部在一个水平线上，怎么样才能调整上下幅度，让图表显示得更直观一点呢？

**Comment by AAChartModel** [comment]
```objc
        AAChartModel *aaChartModel= AAChartModel.new
        .chartTypeSet(AAChartTypeColumn)//图表类型
        .titleSet(@"")//图表主标题
        .subtitleSet(@"")//图表副标题
        .yAxisLineWidthSet(@0)//Y轴轴线线宽为0即是隐藏Y轴轴线
        .colorsThemeSet(@[@"#fe117c",@"#ffc069",@"#06caf4",@"#7dffc0"])//设置主体颜色数组
        .yAxisTitleSet(@"")//设置 Y 轴标题
        .tooltipValueSuffixSet(@"℃")//设置浮动提示框单位后缀
        .backgroundColorSet(@"#4b2b7f")
        .yAxisGridLineWidthSet(@0)//y轴横向分割线宽度为0(即是隐藏分割线)
        .seriesSet(@[
                     AASeriesElement.new
                     .nameSet(@"2017")
                     .dataSet(@[@10.1,@10.2,@10.3,@10.4,@10.5,@10.6,@10.7,@10.8,]),
                     ]
                   );

```

如上, AAChartModel 的 data 数组中的元素值十分接近,绘制成图表便是下图这种效果
<img width="393" alt="2018-10-25 3 03 36" src="https://user-images.githubusercontent.com/16357599/47481802-59863980-d867-11e8-9263-25c7e773cb16.png">

棱柱高度几乎看不到任何起伏


```objc
aaChartModel.yAxisMinSet(@10);
```
为 AAChartModel 实例对象属性`yAxisMin`值设置为10,图表效果如下
<img width="392" alt="2018-10-25 3 03 54" src="https://user-images.githubusercontent.com/16357599/47481922-aff37800-d867-11e8-9616-be6ccc48613a.png">


也就是说,若要让图表能有明显的高低起伏,适当地调整 AAChartModel 的`yAxisMin`(Y轴最小值)即可

**Comment by wncios** [comment]
完美解决，感谢🙏
